Add a git status check, nothing should have changed

diff --git a/.github/workflows/main-go-service.yaml b/.github/workflows/main-go-service.yaml
--- a/.github/workflows/main-go-service.yaml
+++ b/.github/workflows/main-go-service.yaml
@@ -84,6 +84,14 @@ jobs:
         echo "::group::go fmt ./..."
         go fmt ./...
         echo "::endgroup::"
+        
+        echo "::group::git status"
+        if [ -n "$(git status --porcelain)" ]; then
+          echo "Error: The workspace is dirty."
+          git status --porcelain
+          exit 1
+        fi
+        echo "::endgroup::"
 
     - name: Run Go build (amd64)
       env:
